### ISSUE TITLE
Add "Deploying to Heroku" instructions

### ISSUE THREAD

**Issue by ck3g** [ck3g/homebugh#38]
Some people may want to use the application on their own hosting provider. It would be great to provide instructions on how to do that.

Add the step-by-step instructions on how to deploy and run the application on Heroku https://www.heroku.com

**Comment by keivalya** [comment]
I can do that, I've deployed a twitter bot to heroku and I think I can document to do so too!

**Comment by ck3g** [comment]
Perfect!

**Comment by keivalya** [comment]
I hope you won't mind me doing it in October if it's not urgent. I'm a beginner in open source and want to start with HactoberFest.

**Comment by ck3g** [comment]
Not a problem. That's why it's labeled with "Hacktoberferst"

**Comment by NNTin** [comment]
@keivalya I just want to tell you it is not as trivial as you think it might be. It requires a bit of rewrite of the code and it isn't something beginner friendly.

First if you implement Heroku support properly you'd just have a 1-click deployment. ([See how there is no need of me using git or any terminal.](https://www.youtube.com/watch?v=NwPcXBvStSI))

Second [Heroku uses an ephemeral file system](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem).
> During the dyno’s lifetime its running processes can use the filesystem as a temporary scratchpad, but no files that are written are visible to processes in any other dyno and any files written will be **discarded the moment the dyno is stopped or restarted.**

You can't run the database on the Heroku dyno because the file will be lost due to ephemeral filesystem. This means it needs to rely on a database. Which this project is doing -> MySQL. But setting up the database isn't trivial and it is locally hosted. Furthermore you'd exceed the 500 MB quota. For Heroku you need a MySQL database add on. And that you need to integrate into the code.
You also need to make the project bind to $PORT supplied by Heroku.

When you deployed a Twitter bot you didn't have to worry about all that.

Just a heads up. If you manage to do it anyway kudos to you.

**Comment by keivalya** [comment]
@NNTin thank you so much!
I'm just an acquaintance with Databases, not my comfort zone, yet I'll try it once. I hope I'll be able to do so.

Thank you again, your comment is really helpful and definitely looking forward to learning new stuff!

Any kind of resource, you would like to suggest?

**Comment by ck3g** [comment]
Hey @NNTin  thanks for the heads up.

Here are my thoughts on that.

The goal here is not to run the application for production use for lots of users. The goal is to help somebody to set it up on Heroku for their personal use.

There are no file upload features in the application, so there is no need for a filesystem.
As for the database, I think it's well enough to start from the lowest (free) tier, and then anyone can decide to move to the higher tier when (and if) they reach the database size limits.

> For Heroku you need a MySQL database add on.

That's is correct. 

> And that you need to integrate into the code.

I think that's enough to update `config/database.yml` with proper credentials file to complete the integration.

> You also need to make the project bind to $PORT supplied by Heroku.

I don't know that does it mean, but the deployed applications are working fine on port 80.

-------------

In the end, we need to have a simplified version of [Getting Started on Heroku with Rails](https://devcenter.heroku.com/articles/getting-started-with-rails5) specific to that project.

I would suggest starting with very simple instructions and then improve them over time.

**Comment by fabiosoaresv** [comment]
@ck3g Can you check my PR please? https://github.com/ck3g/homebugh/pull/106/
